services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://gitlab.local'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
  gitlab_runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - ./gitlab-runner-mount:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - gitlab:gitlab.local
